* Vectors

- "You can't add apples and oranges". In a strange way, this is the reason for vectors.
- We have two separate numbers $v_1$ and $v_2$. That pair produces a
  *two dimensional vector* $v$

$v = \begin{bmatrix} v_1 \\ v_2 \end{bmatrix}$

** Vector Addition

$v = \begin{bmatrix} v_1 \\ v_2 \end{bmatrix}$

$w = \begin{bmatrix} w_1 \\ w_2 \end{bmatrix}$

$v + w = \begin{bmatrix} v_1 + w_1 \\ v_2 + w_2 \end{bmatrix}$

Subtraction of vectors follow the same idea.

** Scalar Multiplication

$2v = \begin{bmatrix} 2v_1 \\ 2v_2 \end{bmatrix}$

** Zero Vector

The sum of the vector $-v$ and $v$ is the zero vector. This is $\mathbf{0}$
wich is not the same as number zero.

The vector $\mathbf{0}$ has two components $0$ and $0$.

* Linear combination

Combining addition with scalar multiplication, we form *"linear
combinations"* of $v$ and $w$.

The sum of $cv$ and $dw$ is a linear combination of $v$ and $w$.

** Geometrical Interpretation (2D vectors)

- Vector addition produces the diagonal of a prallelogram.
  - [[https://www.khanacademy.org/math/precalculus/x9e81a4f98389efdf:vectors/x9e81a4f98389efdf:vector-add-sub/v/parallelogram-rule-for-vector-addition][Additional Reference]]
- A vector with two components corresponds to a point in the $xy$
  plane.
- The components of $v$ are the coordinates orf the point $x = v_1$
  and $y = v_2$. The arrow ends at this point $(v_1, v_2)$ when it
  starts from $(0,0)$.

** Geometrical Interpretation (3D vectors)

- The vector $v$ corresponds to an arrow in 3-space. Usually the arrow
  starts at the *origin* where the $xyz$ axes meet and the coordinates
  are $(0,0,0)$.

** All combinations

Assuming every $c$, $d$ and $e$ are allowed:

- The combinations $cu$ fill a *line*.
- The combinations $cu + dv$ fill a *plane*.
- The combinations $cu + dv + ew$ fill *three-dimensional space*

* Miscellaneous

- Vectors $\begin{bmatrix} x \\ y \end{bmatrix}$ and $\begin{bmatrix} x
\\ y \\ z \end{bmatrix}$ can also be written as $(x,y)$ and
$(x,y,z)$. Note that they are not a row vector. Row vector are
represented as $[x, y]$ instead.
